### ISSUE TITLE
Fix JOWL endpoints across different SousLeSens modules

### ISSUE THREAD

**Issue by hrssilva** [hrssilva/souslesensVocables#2]
Some SousLeSensVocables modules are not utilizing the correct endpoint paths for the current version of JOWL. This calls need to be consistent with the updated JOWL version available on https://github.com/hrssilva/jowl . This inconsistencies cause various bugs when trying to utilize almost every SLSV's tool.

**Comment by tiagotschmidt** [comment]
Greetings @hrssilva! I've lost some time struggling to overcome some project configurations. As of now, I think I've finally established a stable dev environment. 

Regarding the issue, I searched the [JOWL](https://github.com/hrssilva/jowl) repository. It's an MVC project, so finding the endpoint paths was easy, just searched inside the controller classes. However, I have searched this repository for entry point references of the URLs listed in the axioms controller, and all looked OK. 

Would you mind describing a routine that reproduces one error caused by such an entrypoint path error?
Anything like a file name or test routine would already help.

**Comment by hrssilva** [comment]
Took me a while to check it out, but it seems to have been fixed in a previous commit from source. I didn't catch the change when I synced. The commit 5d1220737dc3a92b98c169ebabc5d85a1f7aa005 fixed it, so I'll be marking this as duplicate and closing it.
